// <auto-generated />
using System;
using GenReport.Domain.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace GenReport.DB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Business.Module", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon_class");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UrlPrefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_prefix");

                    b.HasKey("Id");

                    b.ToTable("modules");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Business.RoleModuleMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("module_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("rolemodulemappings");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.AiConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AiConnectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("ai_connection_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ModelId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AiConnectionId");

                    b.HasIndex("Type");

                    b.HasIndex("Type", "AiConnectionId", "IsActive")
                        .IsUnique()
                        .HasFilter("\"is_active\" = true AND \"model_id\" IS NULL");

                    b.HasIndex("Type", "AiConnectionId", "ModelId", "IsActive")
                        .IsUnique()
                        .HasFilter("\"is_active\" = true AND \"model_id\" IS NOT NULL");

                    b.ToTable("ai_configs");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.AiConnection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("api_key");

                    b.Property<decimal?>("CostPer1kInputTokens")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("cost_per_1k_input_tokens");

                    b.Property<decimal?>("CostPer1kOutputTokens")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("cost_per_1k_output_tokens");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("default_model");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("integer")
                        .HasColumnName("max_tokens");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<int?>("RateLimitRpm")
                        .HasColumnType("integer")
                        .HasColumnName("rate_limit_rpm");

                    b.Property<int?>("RateLimitTpm")
                        .HasColumnType("integer")
                        .HasColumnName("rate_limit_tpm");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("ai_connections");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Intent")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("intent");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("chat_messages");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.ChatSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AiConnectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("ai_connection_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("DatabaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("database_id");

                    b.Property<string>("ModelId")
                        .HasColumnType("text")
                        .HasColumnName("model_id");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AiConnectionId");

                    b.HasIndex("DatabaseId");

                    b.HasIndex("UserId");

                    b.ToTable("chat_sessions");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.Database", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BackupRetentionPolicy")
                        .HasColumnType("text")
                        .HasColumnName("backup_retention_policy");

                    b.Property<int>("BackupSchedule")
                        .HasColumnType("integer")
                        .HasColumnName("backup_schedule");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_string");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatabaseAlias")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("database_alias");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EncryptionMethod")
                        .HasColumnType("text")
                        .HasColumnName("encryption_method");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<string>("SecurityLevel")
                        .HasColumnType("text")
                        .HasColumnName("security_level");

                    b.Property<string>("ServerAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("server_address");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("databases");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.MessageAttachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("MediaFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_file_id");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("MessageId");

                    b.ToTable("message_attachments");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.MessageReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<long>("ReportId")
                        .HasColumnType("bigint")
                        .HasColumnName("report_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("ReportId");

                    b.ToTable("message_reports");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.Query", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CollectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("collection_id");

                    b.Property<string[]>("Comments")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<long>("DatabaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("database_id");

                    b.Property<string[]>("InvolvedColumns")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("involved_columns");

                    b.Property<string[]>("InvolvedTables")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("involved_tables");

                    b.Property<string>("Rawtext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rawtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DatabaseId");

                    b.ToTable("queries");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.Report", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("MediaFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("mediafile_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("NoOfColumns")
                        .HasColumnType("integer")
                        .HasColumnName("no_of_columns");

                    b.Property<int>("NoOfRows")
                        .HasColumnType("integer")
                        .HasColumnName("no_of_rows");

                    b.Property<long>("QueryId")
                        .HasColumnType("bigint")
                        .HasColumnName("query_id");

                    b.Property<int>("TimeInSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("time_in_seconds");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("QueryId");

                    b.ToTable("reports");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.RoutineObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DatabaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("database_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingText")
                        .HasColumnType("text")
                        .HasColumnName("embedding_text");

                    b.Property<string>("FullSchema")
                        .HasColumnType("text")
                        .HasColumnName("full_schema");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("database_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("database_id");

                    b.ToTable("routine_objects", t =>
                        {
                            t.Property("database_id")
                                .HasColumnName("database_id1");
                        });
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.SchemaObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DatabaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("database_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingText")
                        .HasColumnType("text")
                        .HasColumnName("embedding_text");

                    b.Property<string>("FullSchema")
                        .HasColumnType("text")
                        .HasColumnName("full_schema");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("database_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("database_id");

                    b.ToTable("schema_objects", t =>
                        {
                            t.Property("database_id")
                                .HasColumnName("database_id1");
                        });
                });

            modelBuilder.Entity("GenReport.Domain.Entities.Media.MediaFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<string>("StorageUrl")
                        .HasColumnType("text")
                        .HasColumnName("storage_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.ToTable("mediafiles");
                });

            modelBuilder.Entity("GenReport.Domain.Entities.Onboarding.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("ProfileURL")
                        .HasColumnType("text")
                        .HasColumnName("profile_url");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("FirstName");

                    b.HasIndex("LastName");

                    b.ToTable("users");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Business.RoleModuleMapping", b =>
                {
                    b.HasOne("GenReport.DB.Domain.Entities.Business.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.AiConfig", b =>
                {
                    b.HasOne("GenReport.DB.Domain.Entities.Core.AiConnection", "AiConnection")
                        .WithMany()
                        .HasForeignKey("AiConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiConnection");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.ChatMessage", b =>
                {
                    b.HasOne("GenReport.DB.Domain.Entities.Core.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.ChatSession", b =>
                {
                    b.HasOne("GenReport.DB.Domain.Entities.Core.AiConnection", "AiConnection")
                        .WithMany()
                        .HasForeignKey("AiConnectionId");

                    b.HasOne("GenReport.DB.Domain.Entities.Core.Database", "Database")
                        .WithMany()
                        .HasForeignKey("DatabaseId");

                    b.HasOne("GenReport.Domain.Entities.Onboarding.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiConnection");

                    b.Navigation("Database");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.MessageAttachment", b =>
                {
                    b.HasOne("GenReport.Domain.Entities.Media.MediaFile", "MediaFile")
                        .WithMany()
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenReport.DB.Domain.Entities.Core.ChatMessage", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.MessageReport", b =>
                {
                    b.HasOne("GenReport.DB.Domain.Entities.Core.ChatMessage", "Message")
                        .WithMany("Reports")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenReport.DB.Domain.Entities.Core.Report", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.Query", b =>
                {
                    b.HasOne("GenReport.Domain.Entities.Onboarding.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .IsRequired();

                    b.HasOne("GenReport.DB.Domain.Entities.Core.Database", "Database")
                        .WithMany()
                        .HasForeignKey("DatabaseId")
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Database");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.Report", b =>
                {
                    b.HasOne("GenReport.Domain.Entities.Media.MediaFile", "MediaFile")
                        .WithMany()
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenReport.DB.Domain.Entities.Core.Query", "Query")
                        .WithMany()
                        .HasForeignKey("QueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");

                    b.Navigation("Query");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.RoutineObject", b =>
                {
                    b.HasOne("GenReport.DB.Domain.Entities.Core.Database", "Database")
                        .WithMany()
                        .HasForeignKey("database_id");

                    b.Navigation("Database");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.SchemaObject", b =>
                {
                    b.HasOne("GenReport.DB.Domain.Entities.Core.Database", "Database")
                        .WithMany()
                        .HasForeignKey("database_id");

                    b.Navigation("Database");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.ChatMessage", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("GenReport.DB.Domain.Entities.Core.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
